# Train details
date: "2022-10-01"
time: "00:09"
from: "372825009" # Ostrava - Stodolni
from_type: STATION
to: "10202003" # Praha
to_type: CITY
max_changes: 0 # Direct trains only

# Tickets details
preffered_class: C1
tariff: 
  - REGULAR
  - CZECH_STUDENT_PASS_26
  - ISIC
  - ISIC

# Notify.run details
notify_code: <code>
